name: Build Formidable (Pre-Release)

on:
  push:
    branches:
      - pre-release/*

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Electron App
        run: npm run build

      - name: Move installer to installer directory
        shell: pwsh
        run: |
          if (-Not (Test-Path "installer")) {
            New-Item -ItemType Directory -Path "installer" | Out-Null
          }
          Move-Item "dist/Formidable Setup 1.0.0.exe" "installer/Formidable Setup.exe" -Force

      - name: Extract local eSigner CKA portable
        shell: pwsh
        run: |
          Expand-Archive -Path "tools/SSL-eSigner-CKA-portable.zip" -DestinationPath "C:\eSignerCKA" -Force
          Write-Host "== Inhoud van C:\eSignerCKA =="
          Get-ChildItem -Recurse C:\eSignerCKA | ForEach-Object { Write-Host $_.FullName }

      - name: Prepare eSigner config directory
        shell: pwsh
        run: |
          $configPath = "$env:APPDATA\eSignerCKA\Config"
          if (-Not (Test-Path $configPath)) {
            New-Item -Path $configPath -ItemType Directory -Force | Out-Null
          }

      - name: Configure eSigner CKA
        shell: pwsh
        run: |
          & "C:\eSignerCKA\eSignerCKATool.exe" config `
            -mode "${{ secrets.ESIGNER_MODE }}" `
            -user "${{ secrets.ESIGNER_USERNAME }}" `
            -pass "${{ secrets.ESIGNER_PASSWORD }}" `
            -totp "${{ secrets.ESIGNER_TOTP_SECRET }}" `
            -key "C:\eSignerCKA\master.key" -r

      - name: Load certificate into Windows Store
        shell: pwsh
        run: |
          & "C:\eSignerCKA\eSignerCKATool.exe" unload
          & "C:\eSignerCKA\eSignerCKATool.exe" load

      - name: Find cert thumbprint
        id: find_thumbprint
        shell: pwsh
        run: |
          $cert = Get-ChildItem Cert:\CurrentUser\My -CodeSigningCert | Select-Object -First 1
          if (-not $cert) {
            throw "Geen certificaat gevonden in Cert:\CurrentUser\My"
          }
          echo "THUMBPRINT=$($cert.Thumbprint)" >> $env:GITHUB_ENV

      - name: Sign executable
        shell: pwsh
        run: |
          & "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x86\signtool.exe" sign `
            /fd sha256 /tr http://ts.ssl.com /td sha256 `
            /sha1 $env:THUMBPRINT `
            "installer/Formidable Setup.exe"

      - name: Upload signed installer
        uses: actions/upload-artifact@v4
        with:
          name: Formidable Installer (signed)
          path: installer/Formidable Setup.exe

      - name: Create GitHub Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0-pre
          name: Formidable v1.0.0 Pre-Release
          draft: false
          body: |
            ## Pre-Release Notes
            - This is a pre-release version of Formidable.
            - Please test and provide feedback.
            - The final release will be available soon.
          prerelease: true
          files: installer/Formidable Setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
